package com.devsofthewest.iphone.model;

import org.springframework.cloud.gcp.data.datastore.core.mapping.Entity;
import org.springframework.data.annotation.Id;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.annotation.Generated;
import javax.persistence.GeneratedValue;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import com.google.appengine.api.datastore.Text;

@Entity(name = "articless")
public class Article {
    @Id
    Long id;
    Text text;
    Double rating;

    //Constructor for article. Sets rating to 3, and id is autogenerated.
    public Article(Text text, Long id)
    {
        this.text = text;
        this.rating = 3.0;
        this.id = id;
    }

    public Long getId()
    {
        return this.id;
    }

    public void setId(Long id)
    {
        this.id = id;
    }

    public Text getText()
    {
        return this.text;
    }

    public void setText(Text text)
    {
        this.text = text;
    }

    public Double getRating()
    {
        return this.rating;
    }

    public void setRating(Double rating)
    {
        this.rating = rating;
    }

}